# -*- coding: utf-8 -*-
"""Per-URL keyword map from two live Google SERPs (CN, 2026-09-04).

SERP A — "grok bot" (Google rewrite of grokbot):
  Owners: x.ai/bot + sitelinks, grok.com (wrong product), Play, App Store,
  Cursor Help, YouTube, Lenny. Related: Grok 官网, app, Cursor grok bot,
  free, login, android, ios, plan.
  Do not fight x.ai/stores for the exact brand.

SERP B — grokbot / 您是不是要找 grok bot:
  Owners: grokbot.aihuangshu.com (橙皮书×Awesome 合并手册), App Store,
  财联社/东财「企业试用两周」, grokbot.cooking (无关), AWS Grok 广告,
  B站/YouTube, x.ai designing post, treg plugin.
  Domain grokbot.run can compete here as the clean fact hub — not a reprint.

Each URL owns one cluster. Do not repeat the same primary on two pages.
"""

# path -> title, description (110–160), primary, also, do_not
PAGES = {
    "/": {
        "title": "How to start Grok Bot: login, first job, and fixes",
        "description": "How to start Grok Bot: sign in with Cursor, paste one cited job, and use one shared computer. Unofficial handbook. Quit and Retry before you Reset.",
        "h1": "How to start Grok Bot",
        "primary": "Grok Bot guide / grokbot (modifier, not exact brand)",
        "also": "hub for related searches",
        "do_not": "exact 'Grok Bot' vs x.ai; Grok 官网",
    },
    "/learn/what-is-grok-bot/": {
        "title": "What is Grok Bot? Not grok.com, Grok, or Grok Build",
        "description": "What is Grok Bot: a named teammate plus one cloud computer. Why grok.com ranks for grok bot, how it differs from Grok chat, Grok Build, and grok-app.",
        "h1": "What is Grok Bot — not grok.com or Grok Build",
        "primary": "what is grok bot; grok bot vs grok / grok.com",
        "also": "grokbot meaning; grok-app",
        "do_not": "download, pricing numbers",
    },
    "/learn/install/": {
        "title": "Download Grok Bot: official Mac, Windows, Linux, and phone",
        "description": "Official Grok Bot download from x.ai/bot. The top Mac button is Apple silicon; Intel is under More downloads. Then sign in with Cursor.",
        "h1": "Download and install Grok Bot, then sign in with Cursor",
        "primary": "grokbot download; grok bot download; grokbot install",
        "also": "official desktop download; linux package",
        "do_not": "mac-only chip steps; windows tray; phone stores; login popup bugs",
    },
    "/learn/mac-download/": {
        "title": "Grok Bot Mac download: Intel is under More downloads",
        "description": "The top macOS button on x.ai/bot is Apple silicon. Intel is under More downloads. Drag to Applications, choose Open, then sign in with Cursor.",
        "h1": "Download Grok Bot for Mac: the top button is Apple silicon",
        "primary": "grok bot mac download; grokbot mac download; download grok bot for mac",
        "also": "apple silicon; intel; gatekeeper",
        "do_not": "windows installer; iphone app store; weekly usage",
    },
    "/learn/windows-download/": {
        "title": "Grok Bot Windows download and the direct-connection test",
        "description": "Install Grok Bot for Windows from x.ai/bot. Pick x64 or Arm64, keep one copy, and run the staff connection test if the app ignores your proxy.",
        "h1": "Download and install Grok Bot on Windows",
        "primary": "grok bot windows download; grok bot windows install",
        "also": "x64; arm64; tray quit; system proxy",
        "do_not": "mac chip choice; phone stores",
    },
    "/learn/phone-download/": {
        "title": "Grok Bot iPhone and Android download (official stores)",
        "description": "Download Grok Bot for iPhone, iPad, and Android from the official stores. What syncs after Cursor login, and what still requires the desktop app.",
        "h1": "Download Grok Bot for iPhone, iPad, and Android",
        "primary": "grok bot ios download; grok bot android; grok bot app",
        "also": "ipad; app store; google play",
        "do_not": "desktop dmg; reset computer",
    },
    "/learn/login/": {
        "title": "Grok Bot login: finish Cursor in the browser, then return",
        "description": "Sign-in fails when the app loses the browser. Keep Grok Bot open, confirm Cursor succeeded, return manually, and fix Legacy Privacy Mode before Reset.",
        "h1": "Sign in to Grok Bot with your Cursor account",
        "primary": "grok bot login; grokbot sign in; sign in with cursor",
        "also": "sso; privacy mode; stale session",
        "do_not": "cursor ide panel (cursor page); plan price list",
    },
    "/learn/first-bot/": {
        "title": "How to use Grok Bot: create one bot and one job",
        "description": "How to use Grok Bot: name one bot, describe one job, and stop at a draft. A Chief of Staff is optional. Do not open twelve bots on day one.",
        "h1": "How to use Grok Bot: one bot, one job",
        "primary": "how to use grok bot; grok bot tutorial; first grok bot",
        "also": "chief of staff grok bot",
        "do_not": "app download; pricing",
    },
    "/learn/computer/": {
        "title": "What is the Grok Bot computer? One shared cloud PC",
        "description": "The Grok Bot computer is one cloud PC for every bot on the account. Files, cookies, and logins are shared. A second bot is not a private machine.",
        "h1": "What is the Grok Bot computer?",
        "primary": "grok bot computer; shared computer; not a security boundary",
        "also": "isolation; cookies; /workspace",
        "do_not": "can't reach (troubleshooting)",
    },
    "/learn/skills-routines/": {
        "title": "Grok Bot skills, routines, and Teach a task",
        "description": "Grok Bot skills are how; routines are when. Teach a task records about ten minutes of screen, no mic. Save a skill after one good run, then automate.",
        "h1": "Grok Bot skills, routines, and Teach a task",
        "primary": "grok bot skills; grok bot routines; teach a task",
        "also": "grok bot automation",
        "do_not": "plugins/MCP OAuth bugs",
    },
    "/learn/plugins/": {
        "title": "Grok Bot plugins and MCP: connectors before the browser",
        "description": "Grok Bot plugins and remote MCP: prefer connectors over clicking the web. No local stdio. Fixes for Zoom 4700, Gmail, Notion, Canva, X, and GitHub OAuth.",
        "h1": "Grok Bot plugins first, browser as fallback",
        "primary": "grok bot plugins; grok bot mcp; grok bot connectors",
        "also": "zoom 4700; gmail oauth",
        "do_not": "third-party CLI catalog",
    },
    "/learn/operator/": {
        "title": "How operators run Grok Bot after week one",
        "description": "How operators run Grok Bot after week one: one Chief of Staff, Teach a task, a what's-left page, then routines. Named X field posts, no invented bills.",
        "h1": "How operators run Grok Bot after week one",
        "primary": "grok bot chief of staff; grok bot routines; manage grok bots",
        "also": "teach a task; multi-bot; operator",
        "do_not": "first install; invented prices",
    },
    "/learn/ops/": {
        "title": "Grok Bot ops: X, Cursor Cloud Agents, MCP, and the computer",
        "description": "How operators run X, Cursor Cloud Agents, remote MCP, and the shared Grok Bot computer. Named field posts. Drafts stay behind approval.",
        "h1": "How operators run X, Cursor, MCP, and the cloud computer",
        "primary": "grok bot twitter; grok bot x plugin; grok bot cloud agent",
        "also": "grok bot mcp workflow; operate x with grok bot",
        "do_not": "first install; OAuth bug list; isolation lecture; invented prices",
    },
    "/learn/cost-and-pitfalls/": {
        "title": "Grok Bot usage, On-Demand spillover, and cost pitfalls",
        "description": "Grok Bot weekly usage can spill into On-Demand with no in-app warning. How the pool and trial work, eligibility conflicts, and pitfalls that burn the week.",
        "h1": "Grok Bot usage, On-Demand, and cost pitfalls",
        "primary": "grok bot usage; on-demand; weekly pool; trial burns",
        "also": "no in-app warning",
        "do_not": "plan list / is it free (pricing)",
    },
    "/pricing/": {
        "title": "Grok Bot pricing: free, plan, Cursor, enterprise trial",
        "description": "Grok Bot pricing: paid Cursor plans include it, SuperGrok can link, and the early-September enterprise two-week trial is dated. No invented list prices.",
        "h1": "Grok Bot pricing: free, plans, and enterprise trial",
        "primary": "grok bot free; grok bot plan; grokbot pricing; enterprise trial",
        "also": "grok bot cost; 企业试用两周",
        "do_not": "On-Demand spillover mechanics (cost page)",
    },
    "/troubleshooting/": {
        "title": "Grok Bot not working? Quit, Retry, then match the screen",
        "description": "Grok Bot not working: fully quit, choose Retry, and do not Reset while it reconnects. Then match usage, DNS, a white screen, or a hidden Bot.",
        "h1": "Grok Bot not working — quit and Retry before you Reset",
        "primary": "grok bot not working",
        "also": "symptom index; where to start",
        "do_not": "the long walkthroughs for one symptom",
    },
    "/troubleshooting/not-responding/": {
        "title": "Grok Bot not responding: check the computer, then usage",
        "description": "A bot cannot answer while the computer says Reconnecting. If the computer is up and bots are silent, check weekly usage before Recover or Reset.",
        "h1": "Grok Bot not responding: computer first, then usage",
        "primary": "grok bot not responding; grok bot stopped working; bot failed to respond",
        "also": "silent bots; weekly usage; on-demand",
        "do_not": "dns can't reach; white screen; install steps",
    },
    "/troubleshooting/stuck/": {
        "title": "Grok Bot stuck on Setting up? Wait if it is still moving",
        "description": "If Starting your computer is still changing, wait. If it stops: Retry, restart, update the app, then update the computer. Reset is last.",
        "h1": "Grok Bot stuck on Setting up, Starting, or Connecting",
        "primary": "grok bot stuck; stuck on setting up; stuck connecting",
        "also": "cleaning up; 50 percent starting; privacy mode",
        "do_not": "weekly usage silence; mac dmg steps",
    },
    "/troubleshooting/cant-reach/": {
        "title": "Can't reach your computer in Grok Bot? Retry, then DNS",
        "description": "Could not reach Grok Bot's computer: Retry and quit before Reset. If it persists, test a hotspot, wildcard DNS, and the Windows direct-connection check.",
        "h1": "Can't reach your computer in Grok Bot",
        "primary": "can't reach your computer; grok bot reconnecting; cursorvm dns",
        "also": "hotspot; antivirus ssl; vpn",
        "do_not": "silent bots with computer visible; white window config",
    },
    "/troubleshooting/white-screen/": {
        "title": "Grok Bot white screen or missing bots: check Hidden Bots",
        "description": "A white screen can be local config. Missing bots are often hidden or on another device. Do not Reset to look for chats. Chats live outside the computer.",
        "h1": "Grok Bot white screen, empty roster, or hidden bots",
        "primary": "grok bot white screen; grok bot black screen; empty roster",
        "also": "application support; setting up spinner",
        "do_not": "dns walkthrough; recover vs reset table",
    },
    "/troubleshooting/recover-vs-reset/": {
        "title": "Grok Bot Update vs Recover vs Reset: what each removes",
        "description": "Update and Recover keep synced bots and files but remove installed apps. Reset can drop unsynced work. Backup not ready means wait, not Reset.",
        "h1": "Update, Recover, or Reset Grok Bot's computer",
        "primary": "grok bot reset; grok bot recover; update agent computer",
        "also": "cleaning up; last resort",
        "do_not": "usage meter; download packages",
    },
    "/troubleshooting/dns-error/": {
        "title": "Grok Bot DNS error: subdomain lookup, then public DNS",
        "description": "A Grok Bot DNS error means cursorvm.com subdomains are refused while the apex still resolves. Set IPv4 and IPv6 DNS, then quit and reopen.",
        "h1": "Grok Bot DNS error",
        "primary": "grok bot dns error; cursorvm dns",
        "also": "query refused; 1.1.1.1; ipv6",
        "do_not": "windows proxy curl; antivirus issuer",
    },
    "/troubleshooting/plugin-oauth/": {
        "title": "Grok Bot plugin OAuth failed: Gmail, Notion, GitHub",
        "description": "Grok Bot plugin OAuth failed: re-authenticate Notion, connect Gmail from Cursor, and remove a bad GitHub header. Zoom error 4700 has no user fix.",
        "h1": "Grok Bot plugin OAuth failed",
        "primary": "grok bot plugin oauth failed; gmail notion github",
        "also": "zoom 4700; canva ios; x tools=0",
        "do_not": "x login lock; local mcp lesson",
    },
    "/troubleshooting/usage-limit/": {
        "title": "Grok Bot usage limit and on-demand charges explained",
        "description": "A full Grok Bot weekly meter can spill into On-Demand with no in-app warning. Order is weekly pool, then credits, then paid On-Demand. Reset does not refill it.",
        "h1": "Grok Bot usage limit and on-demand charges",
        "primary": "grok bot usage limit; on-demand charges",
        "also": "no warning; bot to bot; weekly pool",
        "do_not": "plan price list (pricing page)",
    },
    "/troubleshooting/install-failed/": {
        "title": "Grok Bot install failed on Mac or Windows",
        "description": "A Grok Bot install failure is the wrong Mac chip, a second Windows copy, or a missing seat. Reinstall does not clear local config.",
        "h1": "Grok Bot install failed on Mac or Windows",
        "primary": "grok bot install failed; mac windows",
        "also": "not supported; two copies; white window",
        "do_not": "full uninstall procedure; linux packages",
    },
    "/troubleshooting/update-failed/": {
        "title": "Grok Bot update failed: app update versus computer update",
        "description": "Two Grok Bot updates: Check for Updates replaces the app. Update under the computer replaces the image and removes installed apps. Keep waiting if it is slow.",
        "h1": "Grok Bot update failed",
        "primary": "grok bot update failed",
        "also": "keep waiting; packages wiped; lost session",
        "do_not": "reset comparison table in full",
    },
    "/troubleshooting/phone-not-connecting/": {
        "title": "Grok Bot phone app not connecting to the computer",
        "description": "The Grok Bot phone app uses the same cloud computer as desktop. If iOS works and desktop does not, do not Reset. Webhook URLs and Always Allow stay on desktop.",
        "h1": "Grok Bot phone app not connecting to the computer",
        "primary": "grok bot phone not connecting; iphone computer",
        "also": "same account; webhook desktop only",
        "do_not": "app store install steps",
    },
    "/troubleshooting/local-execution/": {
        "title": "Grok Bot local computer offline while chat still works",
        "description": "Grok Bot chat can stay up while the local computer is offline. Fully quit and reopen. Always Allow is desktop-only. iOS approves one action at a time.",
        "h1": "Grok Bot local computer offline",
        "primary": "grok bot local computer offline; always allow",
        "also": "local-exec daemon; externalshell",
        "do_not": "linux listmachines keyring",
    },
    "/troubleshooting/linux/": {
        "title": "Grok Bot Linux not connecting: official package first",
        "description": "Use the official Grok Bot deb, rpm, or AppImage from x.ai/bot. Old 0.18 builds were rejected. Empty ListMachines needs an unlocked keyring, then quit.",
        "h1": "Grok Bot Linux not connecting",
        "primary": "grok bot linux not connecting",
        "also": "listmachines; keyring; 0.18 rejected",
        "do_not": "community port catalog",
    },
    "/troubleshooting/trial-ended/": {
        "title": "Grok Bot trial ended: bots stop, export still works",
        "description": "When a Grok Bot trial ends, bots stop answering and data is not deleted. The app can mislabel that as Cant reach your computer. Do not Reset to save the trial.",
        "h1": "Grok Bot trial ended",
        "primary": "grok bot trial ended; access ended",
        "also": "cant reach display bug; export",
        "do_not": "plan prices",
    },
    "/troubleshooting/privacy-mode/": {
        "title": "Grok Bot stuck on Connecting: save Privacy Mode",
        "description": "Grok Bot stuck on Connecting usually means Privacy Mode was never saved. Legacy mode blocks the computer. Save Privacy Mode, fully quit, and reopen.",
        "h1": "Grok Bot stuck on Connecting",
        "primary": "grok bot stuck on connecting; privacy mode",
        "also": "legacy privacy; createagent",
        "do_not": "setting up free plan",
    },
    "/troubleshooting/no-seat/": {
        "title": "Grok Bot stuck on Setting up: free plan or no seat",
        "description": "Endless Setting up your Grok Bot on a free Cursor plan means no computer was provisioned. A team admin role is not a seat. Assign a paid seat, quit, and reopen.",
        "h1": "Grok Bot stuck on Setting up",
        "primary": "grok bot stuck on setting up; free plan",
        "also": "team admin; black spinner",
        "do_not": "privacy mode connecting",
    },
    "/troubleshooting/antivirus/": {
        "title": "Grok Bot blocked by antivirus HTTPS scanning",
        "description": "Antivirus HTTPS scanning can break Grok Bot while the browser still loads. The app trusts public CAs only. Exclude the app or turn scanning off, then quit.",
        "h1": "Grok Bot blocked by antivirus",
        "primary": "grok bot antivirus; ssl scanning",
        "also": "zscaler; warp; public ca",
        "do_not": "windows tun curl",
    },
    "/troubleshooting/windows-proxy/": {
        "title": "Grok Bot Windows proxy: the app connects directly",
        "description": "Grok Bot on Windows ignores the system HTTP proxy and connects directly. A browser check can pass while the app fails. Use TUN, then the noproxy probe.",
        "h1": "Grok Bot ignores the Windows system proxy",
        "primary": "grok bot windows proxy; tun",
        "also": "noproxy curl; awselb 404",
        "do_not": "mac chip choice",
    },
    "/troubleshooting/cloud-agent/": {
        "title": "Grok Bot cloud agent not showing in Cursor",
        "description": "Cloud agents from Grok Bot stay hidden until you enable Source, then Grok Bot, on the agents page and in the desktop sidebar. Once per client.",
        "h1": "Grok Bot cloud agent not showing in Cursor",
        "primary": "grok bot cloud agent not showing",
        "also": "source filter; fast; review-bugbot",
        "do_not": "codebase plugin absence",
    },
    "/troubleshooting/routines/": {
        "title": "Grok Bot routines not running on schedule",
        "description": "A late Grok Bot routine usually fired and waited in a queue. Editing the bot does not break the schedule. The webhook URL is desktop-only.",
        "h1": "Grok Bot routines not running",
        "primary": "grok bot routines not running",
        "also": "next run; webhook desktop; queue",
        "do_not": "weekly usage charge order",
    },
    "/troubleshooting/x-login/": {
        "title": "Grok Bot X login locked on the cloud computer",
        "description": "The Grok Bot cloud computer can hit X risk controls. That lock is not proof the account is broken. Connected with zero X tools has no user-side fix.",
        "h1": "Grok Bot X login locked",
        "primary": "grok bot x login locked",
        "also": "risk controls; x plugin tools=0",
        "do_not": "gmail oauth steps",
    },
    "/troubleshooting/account-unavailable/": {
        "title": "Grok Bot account unavailable after a password change",
        "description": "Grok Bot account unavailable after a password change is usually a stale desktop session. Log out, fully quit, and sign in. The computer is often still there.",
        "h1": "Grok Bot account unavailable",
        "primary": "grok bot account unavailable",
        "also": "password change; too many computers",
        "do_not": "privacy mode; plan price list",
    },
    "/troubleshooting/codebase/": {
        "title": "Grok Bot cannot access your Cursor codebase",
        "description": "Grok Bot has no codebase plugin and does not index your repo. Coding work goes to a Cursor Cloud Agent on a GitHub-connected account.",
        "h1": "Grok Bot cannot access your Cursor codebase",
        "primary": "grok bot codebase; cannot access repo",
        "also": "cloud agent; github integrations",
        "do_not": "source filter steps in full",
    },
    "/learn/": {
        "title": "Grok Bot handbook: lessons from install to first job",
        "description": "Grok Bot handbook in reading order: what it is, install and Cursor login, first Bot, shared computer, skills, plugins, and cost. Start here if you are new.",
        "h1": "Grok Bot handbook — read in this order",
        "primary": "grok bot handbook; grok bot lessons",
        "also": "how grok bot works (order)",
        "do_not": "what is (lesson 1); how to use (first Bot)",
    },
    "/learn/glossary/": {
        "title": "Grok Bot glossary: Bot, computer, skill, routine, plugin",
        "description": "Grok Bot glossary for Bot, shared computer, skill, routine, plugin, MCP, Teach a task, and share templates. Short definitions, not a reprint of the docs.",
        "h1": "Grok Bot glossary",
        "primary": "grok bot glossary; skill vs routine vs plugin",
        "also": "what is a grok bot computer",
        "do_not": "full skills lesson; plugin OAuth bugs",
    },
    "/learn/cursor/": {
        "title": "Cursor Grok Bot: login, usage, and plugins — not the IDE",
        "description": "Cursor grokbot is not a Cursor IDE panel. Grok Bot is its own app: Cursor login, weekly usage, inherited plugins. Ultra is not required on every official page.",
        "h1": "Cursor Grok Bot: one account, two apps",
        "primary": "cursor grokbot; cursor grok bot; grok bot cursor account",
        "also": "cursor login; hermes vs grok bot",
        "do_not": "plan price list; install package steps",
    },
    "/compare/": {
        "title": "Grok Bot alternatives: OpenMausBot, rakazo, gawkbot, OpenClaw",
        "description": "Grok Bot alternatives compared: official managed computer vs OpenMausBot, rakazo, gawkbot, and OpenClaw. When to stay official and when to self-host.",
        "h1": "Grok Bot alternatives — official vs self-hosted",
        "primary": "grok bot alternative; open source grok bot; grok bot vs openclaw",
        "also": "rakazo; gawkbot; OpenMausBot; grokbot github",
        "do_not": "pricing numbers; official app download steps",
    },
    "/use-cases/": {
        "title": "Grok Bot use cases: starter jobs and field examples",
        "description": "Grok Bot use cases: copyable first jobs, X field posts, skills worth installing, and high-star GitHub alternatives. Each card links out.",
        "h1": "Grok Bot use cases — start with one job",
        "primary": "grok bot use cases; grok bot examples",
        "also": "sales; shopping; ops; first job",
        "do_not": "app download; pricing numbers",
    },
    "/tools/": {
        "title": "Grok Bot tools: CLI, TUI, Linux ports, usage meters",
        "description": "Grok Bot tools catalog: 199 CLI, TUI, plugin, MCP, Linux, and usage-meter entries. grok-app is a Grok Build GUI, not a Grok Bot client. Source links included.",
        "h1": "Grok Bot tools catalog",
        "primary": "grok bot tools; grok bot cli (hub)",
        "also": "grok-app disambiguation",
        "do_not": "official app download",
    },
    "/tools/grok-bot-cli/": {
        "title": "grok-bot-cli: terminal roster and messages for Grok Bot",
        "description": "grok-bot-cli is a macOS CLI that reuses a signed-in Grok Bot desktop session to list Bots and send messages. Install notes, risks, and the GitHub source.",
        "h1": "grok-bot-cli",
        "primary": "grok-bot-cli",
        "also": "",
        "do_not": "official app",
    },
    "/tools/grok-bot-skill/": {
        "title": "grok-bot-skill: let coding agents call Grok Bot teammates",
        "description": "grok-bot-skill lets Cursor or Claude coding agents call Grok Bot teammates. How it differs from the official app, install notes, risks, and source.",
        "h1": "grok-bot-skill",
        "primary": "grok-bot-skill",
        "also": "",
        "do_not": "",
    },
    "/tools/grokbot-tui/": {
        "title": "grokbot-tui: terminal UI for Grok Bot",
        "description": "grokbot-tui is a community terminal UI for Grok Bot keyboard workflows. Platforms, install path, differences from the desktop app, risks, and GitHub source.",
        "h1": "grokbot-tui",
        "primary": "grokbot-tui",
        "also": "",
        "do_not": "",
    },
    "/tools/usage-menu-bar/": {
        "title": "Grok Bot weekly usage menu bar for macOS",
        "description": "macOS menu bar meter for Grok Bot weekly usage. Cross-check the Cursor plans screen; install notes, limits, risks, and the upstream GitHub source.",
        "h1": "Grok Bot usage menu bar",
        "primary": "grok bot usage meter; menu bar",
        "also": "",
        "do_not": "pricing table",
    },
    "/tools/linux-port/": {
        "title": "Grok Bot Linux: official packages vs community port",
        "description": "Grok Bot Linux download: prefer official deb, rpm, and AppImage from x.ai/bot. Community port notes, rejected old builds, and GitHub source.",
        "h1": "Grok Bot on Linux: official packages vs community port",
        "primary": "grok bot linux",
        "also": "deb rpm appimage",
        "do_not": "ios/android",
    },
    "/sources/": {
        "title": "Grok Bot sources and fetch notes",
        "description": "Bibliography for this Grok Bot guide: 42 official materials, 89 failure threads, catalog and cases, plus URLs that timed out on fetch day 2026-09-04.",
        "h1": "Sources and fetch notes",
        "primary": "(citation, no head-term fight)",
        "also": "",
        "do_not": "guide / pricing / install",
    },
}


def meta(path):
    return PAGES[path]["title"], PAGES[path]["description"]
