# -*- coding: utf-8 -*-
"""Per-URL keyword map from two live Google SERPs (CN, 2026-09-04).

SERP A — "grok bot" (Google rewrite of grokbot):
  Owners: x.ai/bot + sitelinks, grok.com (wrong product), Play, App Store,
  Cursor Help, YouTube, Lenny. Related: Grok 官网, app, Cursor grok bot,
  free, login, android, ios, plan.
  Do not fight x.ai/stores for the exact brand.

SERP B — grokbot / 您是不是要找 grok bot:
  Owners: grokbot.aihuangshu.com (橙皮书×Awesome 合并手册), App Store,
  财联社/东财「企业试用两周」, grokbot.cooking (无关), AWS Grok 广告,
  B站/YouTube, x.ai designing post, treg plugin.
  Domain grokbot.run can compete here as the clean fact hub — not a reprint.

Each URL owns one cluster. Do not repeat the same primary on two pages.
"""

# path -> title, description (110–160), primary, also, do_not
PAGES = {
    "/openai-dots/": {
        "title": "OpenAI dots: how to turn one on, and how it differs",
        "description": "OpenAI dots are ChatGPT always-on agents on GPT-6 Astra. Who can turn one on, what is not officially announced, and how they differ from Grok Bot and Muse.",
        "h1": "OpenAI dots: how to turn one on, and how it differs",
        "primary": "openai dots; dots gpt; dots ai; chatgpt dots",
        "also": "how to use openai dots; dots vs grok bot; dots vs muse",
        "do_not": "dollar price; OpenAI logo; news rewrite; Alfred demo",
    },
    "/dots-pricing/": {
        "title": "Dots pricing: no separate price is published",
        "description": "Dots pricing from launch reports: the first Dot is included with ChatGPT Pro and Business Premium. No separate OpenAI price sheet is published here.",
        "h1": "Dots pricing: no separate price is published",
        "primary": "dots pricing; dots price",
        "also": "chatgpt pro dots; business premium",
        "do_not": "invent a dollar add-on; repeat the how-to",
    },
    "/dots-release-date/": {
        "title": "Dots release date: DevDay on 29 September 2026",
        "description": "Dots release date is 29 September 2026, OpenAI DevDay in San Francisco. The safety appendix and launch-day reports use that date. Unofficial note.",
        "h1": "Dots release date: 29 September 2026",
        "primary": "dots release date; when did dots launch",
        "also": "openai devday 2026",
        "do_not": "model launch date as the product date; pricing dollars",
    },
    "/dots-download/": {
        "title": "Dots download and app: no separate installer is published",
        "description": "Dots download: launch reports do not name an app-store installer. They place Dots inside ChatGPT, with Slack and Microsoft Teams. Unofficial note.",
        "h1": "Dots download: no separate app is published",
        "primary": "dots download; dots app",
        "also": "chatgpt desktop dot",
        "do_not": "fake store url; pricing",
    },
    "/dots-waitlist/": {
        "title": "Dots waitlist: texting only, no signup link published",
        "description": "Dots waitlist: CNBC describes plan access, not a queue. WIRED uses waitlist for iMessage or RCS texting and does not print a signup URL.",
        "h1": "Dots waitlist: only texting is described that way",
        "primary": "dots waitlist",
        "also": "imessage rcs dots",
        "do_not": "invent a form; general product queue",
    },
    "/dots-vs-grokbot/": {
        "title": "Dots vs Grok Bot: published differences only",
        "description": "Dots vs Grok Bot from published pages. OpenAI's 29 September 2026 agent beside xAI's teammate app. OpenAI's Dots notes do not name Grok Bot.",
        "h1": "Dots vs Grok Bot, from published pages",
        "primary": "dots vs grok bot; dots vs grokbot",
        "also": "openai personal agent vs grok bot",
        "do_not": "claim OpenAI targeted Grok Bot; invented prices",
    },
    "/dots-vs-muse/": {
        "title": "Dots vs Muse: what OpenAI and Meta published",
        "description": "Dots vs Muse from OpenAI's 29 September 2026 notes and Meta's Muse posts. Empty facts stay marked not published. Unofficial comparison.",
        "h1": "Dots vs Muse, from company posts and launch reports",
        "primary": "dots vs muse",
        "also": "openai dots vs meta muse",
        "do_not": "invent feature parity; today's app rank",
    },
    "/dots-alternatives/": {
        "title": "Dots alternatives: Muse, Grok Bot, and OpenClaw",
        "description": "Dots alternatives named in launch coverage: Meta's Muse, xAI's Grok Bot, and OpenClaw as WIRED mentions it. Unofficial, with no invented ranking.",
        "h1": "Dots alternatives named in public reports",
        "primary": "dots alternatives",
        "also": "dots vs similar agents",
        "do_not": "ranked best list; fake downloads",
    },
    "/dots-faq/": {
        "title": "Dots FAQ: official page, Alfred, and training",
        "description": "Dots FAQ for what the launch sources do not support: this is not OpenAI's site, and those sources do not name an Alfred agent. Pointers included.",
        "h1": "Dots FAQ: official page, Alfred, and training",
        "primary": "dots faq; alfred agent dots",
        "also": "is dots official",
        "do_not": "describe an Alfred demo; repeat pricing essay",
    },
    "/muse/": {
        "title": "What is Muse? Meta's personal agent, with sources",
        "description": "What Muse is, how to start it, and the reported 20 and 100 dollar tiers. Meta personal agent on Muse Secure VM. Unofficial notes.",
        "h1": "What is Muse, Meta's personal agent",
        "primary": "what is muse; muse ai; muse agent; muse app",
        "also": "meta muse personal agent; muse price; how to use muse",
        "do_not": "OpenAI logo; unattributed muse price; claim today's chart rank",
    },
    "/muse-vs/": {
        "title": "Muse vs Dots and Muse vs Grok Bot",
        "description": "Muse vs Dots and Muse vs Grok Bot from Meta's posts, OpenAI's 29 September 2026 notes, and x.ai/bot. Unofficial, and not a copied Dots essay.",
        "h1": "Muse vs Dots and Muse vs Grok Bot",
        "primary": "muse vs; muse vs dots; muse vs grok bot",
        "also": "muse comparison",
        "do_not": "repeat the full dots table; invented prices",
    },
    "/muse-alternatives/": {
        "title": "Muse alternatives: Dots, Grok Bot, and OpenClaw",
        "description": "Muse alternatives named in public coverage: OpenAI Dots, xAI Grok Bot, and OpenClaw as WIRED mentions it. Unofficial notes, no invented ranking.",
        "h1": "Muse alternatives named in public reports",
        "primary": "muse alternatives",
        "also": "muse vs other agents",
        "do_not": "ranked list; fake store links",
    },
    "/muse-vs-grok-bot/": {
        "title": "Muse vs Grok Bot: where they differ, by their own pages",
        "description": "Muse vs Grok Bot row by row from Meta's and xAI's own pages: shared computer, approvals, passwords, access, and how to choose. Unofficial notes.",
        "h1": "Muse vs Grok Bot: where they differ, by their own pages",
        "primary": "muse vs grok bot; muse vs grokbot",
        "also": "muse or grok bot; meta muse vs xai grok bot",
        "do_not": "repeat the /muse-vs/ short row; invented prices; claim Meta targets Grok Bot",
    },
    "/dots-security-privacy/": {
        "title": "Dots security and privacy: what OpenAI says and tested",
        "description": "Dots security and privacy from OpenAI's own pages: sandboxing, secure sign-in, Auto-review, training settings, test numbers, and known limits. Unofficial.",
        "h1": "Dots security and privacy: what OpenAI says and tested",
        "primary": "dots security; dots privacy; is dots safe",
        "also": "dots permissions; dots prompt injection; dots training data; dots custom rules",
        "do_not": "claim independent audit; invent incident details; describe secrets as safe in chat",
    },
    "/dots-vs-chatgpt/": {
        "title": "Dots vs ChatGPT, and how Claude differs",
        "description": "Dots vs ChatGPT from OpenAI's Help Center, plus what Anthropic publishes about Claude Cowork. No invented head-to-head. Unofficial notes.",
        "h1": "Dots vs ChatGPT, and how Claude differs",
        "primary": "dots vs chatgpt; dots vs claude",
        "also": "difference between dots and chatgpt; openai dots vs claude cowork",
        "do_not": "invent Claude equivalence; benchmark claims; claim Plus gets dots",
    },
    "/how-to-get-openai-dots/": {
        "title": "How to get OpenAI dots: plan, region, and setup",
        "description": "How to get OpenAI dots: which plans and regions are listed, the desktop-only setup order, and what is not available yet. Unofficial notes.",
        "h1": "How to get OpenAI dots: plan, region, and setup",
        "primary": "how to get openai dots; dots eligibility",
        "also": "dots availability; who can use dots; how to create a dot; dots region",
        "do_not": "claim Plus access; invent EU date; invent app links",
    },
    "/dots-not-officially-announced/": {
        "title": "Dots: what is not officially announced",
        "description": "What OpenAI has not announced for dots, or marked coming soon, limited beta, or unavailable at launch, in one sourced table. Unofficial notes.",
        "h1": "Dots: what is not officially announced",
        "primary": "dots not officially announced; dots coming soon",
        "also": "dots limitations; dots rumors; dots unannounced features",
        "do_not": "present rumor as fact; invent dates; cite forum comments as sources",
    },
    "/": {
        "title": "Grok Bot guide: install, Cursor login, and do not Reset first",
        "description": "Unofficial Grok Bot guide. Install from x.ai/bot, sign in with Cursor, use one shared computer, and Retry before you Reset.",
        "h1": "How to start Grok Bot without burning a week",
        "primary": "Grok Bot guide / grokbot (modifier, not exact brand)",
        "also": "hub for related searches",
        "do_not": "exact 'Grok Bot' vs x.ai; Grok 官网",
    },
    "/learn/what-is-grok-bot/": {
        "title": "What is Grok Bot? Not grok.com, Grok, or Grok Build",
        "description": "What is Grok Bot: a named teammate plus one cloud computer. Why grok.com ranks for grok bot, how it differs from Grok chat, Grok Build, and grok-app.",
        "h1": "What is Grok Bot — not grok.com or Grok Build",
        "primary": "what is grok bot; grok bot vs grok / grok.com",
        "also": "grokbot meaning; grok-app",
        "do_not": "download, pricing numbers",
    },
    "/learn/install/": {
        "title": "Download Grok Bot: official Mac, Windows, Linux, and phone",
        "description": "Official Grok Bot download from x.ai/bot. The top Mac button is Apple silicon; Intel is under More downloads. Then sign in with Cursor.",
        "h1": "Download and install Grok Bot, then sign in with Cursor",
        "primary": "grokbot download; grok bot download; grokbot install",
        "also": "official desktop download; linux package",
        "do_not": "mac-only chip steps; windows tray; phone stores; login popup bugs",
    },
    "/learn/mac-download/": {
        "title": "Grok Bot Mac download: Intel is under More downloads",
        "description": "The top macOS button on x.ai/bot is Apple silicon. Intel is under More downloads. Drag to Applications, choose Open, then sign in with Cursor.",
        "h1": "Download Grok Bot for Mac: the top button is Apple silicon",
        "primary": "grok bot mac download; grokbot mac download; download grok bot for mac",
        "also": "apple silicon; intel; gatekeeper",
        "do_not": "windows installer; iphone app store; weekly usage",
    },
    "/learn/windows-download/": {
        "title": "Grok Bot Windows download and the direct-connection test",
        "description": "Install Grok Bot for Windows from x.ai/bot. Pick x64 or Arm64, keep one copy, and run the staff connection test if the app ignores your proxy.",
        "h1": "Download and install Grok Bot on Windows",
        "primary": "grok bot windows download; grok bot windows install",
        "also": "x64; arm64; tray quit; system proxy",
        "do_not": "mac chip choice; phone stores",
    },
    "/learn/phone-download/": {
        "title": "Grok Bot iPhone and Android download (official stores)",
        "description": "Download Grok Bot for iPhone, iPad, and Android from the official stores. What syncs after Cursor login, and what still requires the desktop app.",
        "h1": "Download Grok Bot for iPhone, iPad, and Android",
        "primary": "grok bot ios download; grok bot android; grok bot app",
        "also": "ipad; app store; google play",
        "do_not": "desktop dmg; reset computer",
    },
    "/learn/login/": {
        "title": "Grok Bot login: finish Cursor in the browser, then return",
        "description": "Sign-in fails when the app loses the browser. Keep Grok Bot open, confirm Cursor succeeded, return manually, and fix Legacy Privacy Mode before Reset.",
        "h1": "Sign in to Grok Bot with your Cursor account",
        "primary": "grok bot login; grokbot sign in; sign in with cursor",
        "also": "sso; privacy mode; stale session",
        "do_not": "cursor ide panel (cursor page); plan price list",
    },
    "/learn/first-bot/": {
        "title": "How to use Grok Bot: one first Bot, then a draft",
        "description": "How to use Grok Bot: name one Bot, paste a cited brief, and stop at a draft. A Chief of Staff is optional. Do not open twelve Bots on day one.",
        "h1": "How to use Grok Bot: first Bot and Chief of Staff",
        "primary": "how to use grok bot; grok bot tutorial; first grok bot",
        "also": "chief of staff grok bot",
        "do_not": "app download; pricing",
    },
    "/learn/computer/": {
        "title": "Grok Bot computer: one shared cloud PC for every Bot",
        "description": "The Grok Bot computer is one cloud machine for every Bot on the account. Screens are not private. Chats are stored outside it. Recover before Reset.",
        "h1": "The Grok Bot computer is shared — not a security boundary",
        "primary": "grok bot computer; shared computer; not a security boundary",
        "also": "isolation; cookies; /workspace",
        "do_not": "can't reach (troubleshooting)",
    },
    "/learn/skills-routines/": {
        "title": "Grok Bot skills, routines, and Teach a task",
        "description": "Grok Bot skills are how; routines are when. Teach a task records about ten minutes of screen, no mic. Save a skill after one good run, then automate.",
        "h1": "Grok Bot skills, routines, and Teach a task",
        "primary": "grok bot skills; grok bot routines; teach a task",
        "also": "grok bot automation",
        "do_not": "plugins/MCP OAuth bugs",
    },
    "/learn/plugins/": {
        "title": "Grok Bot plugins and MCP: connectors before the browser",
        "description": "Grok Bot plugins and remote MCP: prefer connectors over clicking the web. No local stdio. Fixes for Zoom 4700, Gmail, Notion, Canva, X, and GitHub OAuth.",
        "h1": "Grok Bot plugins first, browser as fallback",
        "primary": "grok bot plugins; grok bot mcp; grok bot connectors",
        "also": "zoom 4700; gmail oauth",
        "do_not": "third-party CLI catalog",
    },
    "/learn/operator/": {
        "title": "How operators run Grok Bot after week one",
        "description": "How operators run Grok Bot after week one: one Chief of Staff, Teach a task, a what's-left page, then routines. Named X field posts, no invented bills.",
        "h1": "How operators run Grok Bot after week one",
        "primary": "grok bot chief of staff; grok bot routines; manage grok bots",
        "also": "teach a task; multi-bot; operator",
        "do_not": "first install; invented prices",
    },
    "/learn/ops/": {
        "title": "Grok Bot ops: X, Cursor Cloud Agents, MCP, and the computer",
        "description": "How operators run X, Cursor Cloud Agents, remote MCP, and the shared Grok Bot computer. Named field posts. Drafts stay behind approval.",
        "h1": "How operators run X, Cursor, MCP, and the cloud computer",
        "primary": "grok bot twitter; grok bot x plugin; grok bot cloud agent",
        "also": "grok bot mcp workflow; operate x with grok bot",
        "do_not": "first install; OAuth bug list; isolation lecture; invented prices",
    },
    "/learn/cost-and-pitfalls/": {
        "title": "Grok Bot usage, On-Demand spillover, and cost pitfalls",
        "description": "Grok Bot weekly usage can spill into On-Demand with no in-app warning. How the pool and trial work, eligibility conflicts, and pitfalls that burn the week.",
        "h1": "Grok Bot usage, On-Demand, and cost pitfalls",
        "primary": "grok bot usage; on-demand; weekly pool; trial burns",
        "also": "no in-app warning",
        "do_not": "plan list / is it free (pricing)",
    },
    "/pricing/": {
        "title": "Grok Bot pricing: free, plan, Cursor, enterprise trial",
        "description": "Grok Bot pricing: paid Cursor plans include it, SuperGrok can link, and the early-September enterprise two-week trial is dated. No invented list prices.",
        "h1": "Grok Bot pricing: free, plans, and enterprise trial",
        "primary": "grok bot free; grok bot plan; grokbot pricing; enterprise trial",
        "also": "grok bot cost; 企业试用两周",
        "do_not": "On-Demand spillover mechanics (cost page)",
    },
    "/troubleshooting/": {
        "title": "Grok Bot not working? Quit, Retry, then match the screen",
        "description": "Grok Bot not working: fully quit, choose Retry, and do not Reset while it reconnects. Then match usage, DNS, a white screen, or a hidden Bot.",
        "h1": "Grok Bot not working — quit and Retry before you Reset",
        "primary": "grok bot not working",
        "also": "symptom index; where to start",
        "do_not": "the long walkthroughs for one symptom",
    },
    "/troubleshooting/not-responding/": {
        "title": "Grok Bot not responding: check the computer, then usage",
        "description": "A bot cannot answer while the computer says Reconnecting. If the computer is up and bots are silent, check weekly usage before Recover or Reset.",
        "h1": "Grok Bot not responding: computer first, then usage",
        "primary": "grok bot not responding; grok bot stopped working; bot failed to respond",
        "also": "silent bots; weekly usage; on-demand",
        "do_not": "dns can't reach; white screen; install steps",
    },
    "/troubleshooting/stuck/": {
        "title": "Grok Bot stuck on Setting up? Wait if it is still moving",
        "description": "If Starting your computer is still changing, wait. If it stops: Retry, restart, update the app, then update the computer. Reset is last.",
        "h1": "Grok Bot stuck on Setting up, Starting, or Connecting",
        "primary": "grok bot stuck; stuck on setting up; stuck connecting",
        "also": "cleaning up; 50 percent starting; privacy mode",
        "do_not": "weekly usage silence; mac dmg steps",
    },
    "/troubleshooting/cant-reach/": {
        "title": "Can't reach your computer in Grok Bot? Retry, then DNS",
        "description": "Could not reach Grok Bot's computer: Retry and quit before Reset. If it persists, test a hotspot, wildcard DNS, and the Windows direct-connection check.",
        "h1": "Can't reach your computer in Grok Bot",
        "primary": "can't reach your computer; grok bot reconnecting; cursorvm dns",
        "also": "hotspot; antivirus ssl; vpn",
        "do_not": "silent bots with computer visible; white window config",
    },
    "/troubleshooting/white-screen/": {
        "title": "Grok Bot white screen or missing bots: check Hidden Bots",
        "description": "A white screen can be local config. Missing bots are often hidden or on another device. Do not Reset to look for chats. Chats live outside the computer.",
        "h1": "Grok Bot white screen, empty roster, or hidden bots",
        "primary": "grok bot white screen; grok bot black screen; empty roster",
        "also": "application support; setting up spinner",
        "do_not": "dns walkthrough; recover vs reset table",
    },
    "/troubleshooting/recover-vs-reset/": {
        "title": "Grok Bot Update vs Recover vs Reset: what each removes",
        "description": "Update and Recover keep synced bots and files but remove installed apps. Reset can drop unsynced work. Backup not ready means wait, not Reset.",
        "h1": "Update, Recover, or Reset Grok Bot's computer",
        "primary": "grok bot reset; grok bot recover; update agent computer",
        "also": "cleaning up; last resort",
        "do_not": "usage meter; download packages",
    },
    "/troubleshooting/plugin-oauth/": {
        "title": "Grok Bot plugin OAuth failed: Gmail, Notion, GitHub",
        "description": "Grok Bot plugin OAuth failed: reopen the auth tab, then the staff fix for Gmail, Notion, GitHub, Zoom 4700, Canva, and X. Do not paste tokens.",
        "h1": "Grok Bot plugin OAuth failed",
        "primary": "grok bot plugin oauth failed; gmail notion github",
        "also": "zoom 4700; canva redirect",
        "do_not": "weekly usage; reset versus recover table",
    },
    "/troubleshooting/usage-limit/": {
        "title": "Grok Bot usage limit and On-Demand charges, without a Reset",
        "description": "A full Grok Bot weekly pool looks like a silent bot. Read Usage before Reset. On-Demand can start with no in-app warning. Prices stay on the pricing page.",
        "h1": "Grok Bot usage limit",
        "primary": "grok bot usage limit; on-demand charges",
        "also": "silent bots; weekly pool",
        "do_not": "plan price table; dns walkthrough",
    },
    "/troubleshooting/dns-error/": {
        "title": "Grok Bot DNS error: cursorvm.com lookup refused",
        "description": "Grok Bot DNS error: the computer hostname under cursorvm.com is refused while the apex still answers. Set IPv4 and IPv6 DNS, or use a hotspot, before Reset.",
        "h1": "Grok Bot DNS error",
        "primary": "grok bot dns error; cursorvm.com",
        "also": "query refused; ipv6 dns",
        "do_not": "full cant-reach button order; usage meter",
    },
    "/troubleshooting/install-failed/": {
        "title": "Grok Bot install failed on Mac or Windows",
        "description": "Grok Bot install failed usually means the wrong Mac chip, two Windows copies, or no computer on a free plan. The same file again does not fix it.",
        "h1": "Grok Bot install failed on Mac or Windows",
        "primary": "grok bot install failed mac; grok bot install failed windows",
        "also": "not supported; two copies",
        "do_not": "intel download walkthrough; phone stores",
    },
    "/troubleshooting/update-failed/": {
        "title": "Grok Bot update failed: keep waiting before Reset",
        "description": "Grok Bot update failed: the app update and the computer update are different buttons. Backup not ready and a slow image mean wait. Reset is not the first click.",
        "h1": "Grok Bot update failed",
        "primary": "grok bot update failed",
        "also": "backup not ready; restart to update",
        "do_not": "full recover versus reset table; usage meter",
    },
    "/troubleshooting/phone-not-connecting/": {
        "title": "Grok Bot phone not connecting to the computer",
        "description": "The Grok Bot phone app shares the cloud computer. It does not attach to the laptop. If the phone works and the desktop is black, do not Reset.",
        "h1": "Grok Bot phone app not connecting to computer",
        "primary": "grok bot phone not connecting; iphone not connecting to computer",
        "also": "same account; cellular",
        "do_not": "app store install steps; weekly usage essay",
    },
    "/troubleshooting/uninstall/": {
        "title": "How to uninstall Grok Bot without deleting Cursor",
        "description": "Uninstalling Grok Bot removes the app and leaves the Cursor account. iOS Delete Account and the dashboard control delete the account, bots, chats, and computer.",
        "h1": "How to uninstall Grok Bot",
        "primary": "how to uninstall grok bot",
        "also": "delete account; sign out",
        "do_not": "reset versus recover table; prices",
    },
    "/learn/is-grok-bot-free/": {
        "title": "Is Grok Bot free? Trial, plans, and no separate price",
        "description": "Grok Bot is not a consumer free tier and not its own product to buy. Access comes with Cursor or a linkable SuperGrok plan. Prices stay on the pricing page.",
        "h1": "Is Grok Bot free",
        "primary": "is grok bot free",
        "also": "free trial; no separate sku",
        "do_not": "eligibility table and USD; on-demand mechanics",
    },
    "/troubleshooting/linux-setup/": {
        "title": "Grok Bot Linux setup failed: official package first",
        "description": "Grok Bot Linux setup failed on rejected old builds. Use the official deb, rpm, or AppImage from x.ai/bot. A community port is not staff support.",
        "h1": "Grok Bot Linux setup failed",
        "primary": "grok bot linux setup failed; grok bot linux not working",
        "also": "0.18 rejected; listmachines",
        "do_not": "community port catalog essay; mac chip",
    },
    "/troubleshooting/local-computer/": {
        "title": "Grok Bot local computer not connected",
        "description": "Grok Bot local computer not connected is the helper on your machine, not a dead cloud computer. Fully quit and re-register before you Recover or Reset.",
        "h1": "Grok Bot local computer not connected",
        "primary": "grok bot local computer not connected; local execution offline",
        "also": "local-exec-daemon; always allow",
        "do_not": "cloud recover table; dns",
    },
    "/troubleshooting/routine-did-not-run/": {
        "title": "Grok Bot routine did not run: check the queue",
        "description": "A Grok Bot routine that did not run is often disabled, in the wrong time zone, paused for usage, or sitting in a queue. Do not delete it as the first step.",
        "h1": "Grok Bot routine did not run",
        "primary": "grok bot routine did not run; grok bot routines not running",
        "also": "next run run now; webhook url",
        "do_not": "skill authoring lesson; usage prices",
    },
    "/troubleshooting/approval-stuck/": {
        "title": "Grok Bot approval needed stuck after the card times out",
        "description": "Grok Bot approval needed stuck is usually a card that timed out, or an Ask first rule that beats Allow automatically. Reset does not clear the rule.",
        "h1": "Grok Bot approval needed stuck",
        "primary": "grok bot approval needed stuck",
        "also": "ask first; auto-review",
        "do_not": "password takeover; usage meter",
    },
    "/troubleshooting/attachment/": {
        "title": "Grok Bot attachment cannot be read",
        "description": "Grok Bot cannot read an attachment over the size cap, still uploading, encrypted, or unsupported. Wait for the thumbnail. Six files is the desktop maximum.",
        "h1": "Grok Bot attachment cannot be read",
        "primary": "grok bot attachment cannot be read",
        "also": "25 mb; thumbnail",
        "do_not": "gmail oauth essay; reset table",
    },
    "/troubleshooting/sign-in/": {
        "title": "Grok Bot sign-in does not complete",
        "description": "Grok Bot sign-in fails when the browser popup is lost, Legacy Privacy Mode is unsaved, or the Mac kept an expired session. There is no second account.",
        "h1": "Grok Bot sign-in does not complete",
        "primary": "grok bot sign-in does not complete; grok bot login failed",
        "also": "privacy mode; expired session",
        "do_not": "normal login lesson; plan prices",
    },
    "/troubleshooting/waiting-for-login/": {
        "title": "Grok Bot stuck waiting for a login or approval",
        "description": "Grok Bot stuck waiting for login means take over the computer and sign in yourself. Do not paste a password or code into chat. Reset is the wrong button.",
        "h1": "Grok Bot stuck waiting for login",
        "primary": "grok bot stuck waiting for login; take over computer",
        "also": "captcha; do not paste password",
        "do_not": "cursor sign-in popup; approval rule essay",
    },
    "/about/": {
        "title": "About this unofficial Grok Bot guide",
        "description": "What grokbot.run is: an unofficial handbook for Grok Bot, how facts are chosen, and what the site will not invent. Not an xAI or Cursor site.",
        "h1": "About this Grok Bot guide",
        "primary": "about grok bot guide",
        "also": "unofficial",
        "do_not": "product support; prices",
    },
    "/privacy/": {
        "title": "Privacy policy for the Grok Bot guide",
        "description": "Privacy for grokbot.run: no site account, optional GA4 cookies only when a measurement ID is set, and ads may be shown in the future.",
        "h1": "Privacy policy",
        "primary": "privacy policy",
        "also": "cookies; analytics; ads",
        "do_not": "cursor privacy policy reprint",
    },
    "/terms/": {
        "title": "Terms of use for the Grok Bot guide",
        "description": "Terms for using this unofficial Grok Bot handbook. Not a product warranty, not official docs, and not a price quote. Official pages win on conflict.",
        "h1": "Terms of use",
        "primary": "terms of use",
        "also": "unofficial handbook",
        "do_not": "product terms of service",
    },
    "/contact/": {
        "title": "Contact the Grok Bot guide",
        "description": "Contact this handbook at hello@grokbot.run. Product problems go to hi@cursor.com. This site cannot see your Cursor account or reset a computer.",
        "h1": "Contact this guide",
        "primary": "contact grok bot guide",
        "also": "hello@grokbot.run",
        "do_not": "product support form",
    },
    "/learn/": {
        "title": "Grok Bot handbook: lessons from install to first job",
        "description": "Grok Bot handbook in reading order: what it is, install and Cursor login, first Bot, shared computer, skills, plugins, and cost. Start here if you are new.",
        "h1": "Grok Bot handbook — read in this order",
        "primary": "grok bot handbook; grok bot lessons",
        "also": "how grok bot works (order)",
        "do_not": "what is (lesson 1); how to use (first Bot)",
    },
    "/learn/glossary/": {
        "title": "Grok Bot glossary: Bot, computer, skill, routine, plugin",
        "description": "Grok Bot glossary for Bot, shared computer, skill, routine, plugin, MCP, Teach a task, and share templates. Short definitions, not a reprint of the docs.",
        "h1": "Grok Bot glossary",
        "primary": "grok bot glossary; skill vs routine vs plugin",
        "also": "what is a grok bot computer",
        "do_not": "full skills lesson; plugin OAuth bugs",
    },
    "/learn/cursor/": {
        "title": "Cursor Grok Bot: login, usage, and plugins — not the IDE",
        "description": "Cursor grokbot is not a Cursor IDE panel. Grok Bot is its own app: Cursor login, weekly usage, inherited plugins. Ultra is not required on every official page.",
        "h1": "Cursor Grok Bot: one account, two apps",
        "primary": "cursor grokbot; cursor grok bot; grok bot cursor account",
        "also": "cursor login; hermes vs grok bot",
        "do_not": "plan price list; install package steps",
    },
    "/compare/": {
        "title": "Grok Bot alternatives: OpenMausBot, rakazo, gawkbot, OpenClaw",
        "description": "Grok Bot alternatives compared: official managed computer vs OpenMausBot, rakazo, gawkbot, and OpenClaw. When to stay official and when to self-host.",
        "h1": "Grok Bot alternatives — official vs self-hosted",
        "primary": "grok bot alternative; open source grok bot; grok bot vs openclaw",
        "also": "rakazo; gawkbot; OpenMausBot; grokbot github",
        "do_not": "pricing numbers; official app download steps",
    },
    "/use-cases/": {
        "title": "Grok Bot use cases: starter jobs and field examples",
        "description": "Grok Bot use cases: copyable first jobs, X field posts, skills worth installing, and high-star GitHub alternatives. Each card links out.",
        "h1": "Grok Bot use cases — start with one job",
        "primary": "grok bot use cases; grok bot examples",
        "also": "sales; shopping; ops; first job",
        "do_not": "app download; pricing numbers",
    },
    "/tools/": {
        "title": "Grok Bot tools: CLI, TUI, Linux ports, usage meters",
        "description": "Grok Bot tools catalog: 199 CLI, TUI, plugin, MCP, Linux, and usage-meter entries. grok-app is a Grok Build GUI, not a Grok Bot client. Source links included.",
        "h1": "Grok Bot tools catalog",
        "primary": "grok bot tools; grok bot cli (hub)",
        "also": "grok-app disambiguation",
        "do_not": "official app download",
    },
    "/tools/grok-bot-cli/": {
        "title": "grok-bot-cli: terminal roster and messages for Grok Bot",
        "description": "grok-bot-cli is a macOS CLI that reuses a signed-in Grok Bot desktop session to list Bots and send messages. Install notes, risks, and the GitHub source.",
        "h1": "grok-bot-cli",
        "primary": "grok-bot-cli",
        "also": "",
        "do_not": "official app",
    },
    "/tools/grok-bot-skill/": {
        "title": "grok-bot-skill: let coding agents call Grok Bot teammates",
        "description": "grok-bot-skill lets Cursor or Claude coding agents call Grok Bot teammates. How it differs from the official app, install notes, risks, and source.",
        "h1": "grok-bot-skill",
        "primary": "grok-bot-skill",
        "also": "",
        "do_not": "",
    },
    "/tools/grokbot-tui/": {
        "title": "grokbot-tui: terminal UI for Grok Bot",
        "description": "grokbot-tui is a community terminal UI for Grok Bot keyboard workflows. Platforms, install path, differences from the desktop app, risks, and GitHub source.",
        "h1": "grokbot-tui",
        "primary": "grokbot-tui",
        "also": "",
        "do_not": "",
    },
    "/tools/usage-menu-bar/": {
        "title": "Grok Bot weekly usage menu bar for macOS",
        "description": "macOS menu bar meter for Grok Bot weekly usage. Cross-check the Cursor plans screen; install notes, limits, risks, and the upstream GitHub source.",
        "h1": "Grok Bot usage menu bar",
        "primary": "grok bot usage meter; menu bar",
        "also": "",
        "do_not": "pricing table",
    },
    "/tools/linux-port/": {
        "title": "Grok Bot Linux: official packages vs community port",
        "description": "Grok Bot Linux download: prefer official deb, rpm, and AppImage from x.ai/bot. Community port notes, rejected old builds, and GitHub source.",
        "h1": "Grok Bot on Linux: official packages vs community port",
        "primary": "grok bot linux",
        "also": "deb rpm appimage",
        "do_not": "ios/android",
    },
    "/sources/": {
        "title": "Grok Bot sources and fetch notes",
        "description": "Bibliography for this Grok Bot guide: 42 official materials, 89 failure threads, catalog and cases, plus URLs that timed out on fetch day 2026-09-04.",
        "h1": "Sources and fetch notes",
        "primary": "(citation, no head-term fight)",
        "also": "",
        "do_not": "guide / pricing / install",
    },
}


def meta(path):
    return PAGES[path]["title"], PAGES[path]["description"]
